In [33]:
#  Question 1. importing  CSV file
import pandas as pd
df = pd.read_csv("/content/retail_dataset .csv")
df
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    100 non-null    object
 1   Customer ID       100 non-null    object
 2   Product Category  97 non-null     object
 3   Quantity          98 non-null     float64
 4   Price             95 non-null     float64
 5   Date              100 non-null    object
 6   Region            98 non-null     object
dtypes: float64(2), object(5)
memory usage: 5.6+ KB

In [28]:
# Question 2. find missing value in netitre dataset.
total_missing = df.isnull().sum()

print("Total missing values in the dataset:", total_missing)

Total missing values in the dataset: Transaction ID      0
Customer ID         0
Product Category    3
Quantity            2
Price               5
Date                0
Region              2
dtype: int64

In [37]:
# Queastion 3. fill missing value with mean
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].mean())
df["Price"] = df["Price"].fillna(df["Price"].mean())
df

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West
...,...,...,...,...,...,...,...
95,T096,C036,Furniture,10.0,2901.0,08-08-2023,North
96,T097,C021,Clothing,9.0,1077.0,19-07-2024,North
97,T098,C015,Clothing,7.0,643.0,13-08-2023,North
98,T099,C005,Groceries,9.0,429.0,20-01-2024,South
99,T100,C010,Furniture,8.0,1183.0,07-02-2024,North

In [45]:
# Question 4 removing row where exist missing value. category and region. dropna ke sath subset use hota hai.
df = df.dropna(subset=["Product Category", "Region"])
df

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West
...,...,...,...,...,...,...,...
95,T096,C036,Furniture,10.0,2901.0,08-08-2023,North
96,T097,C021,Clothing,9.0,1077.0,19-07-2024,North
97,T098,C015,Clothing,7.0,643.0,13-08-2023,North
98,T099,C005,Groceries,9.0,429.0,20-01-2024,South
99,T100,C010,Furniture,8.0,1183.0,07-02-2024,North

In [47]:
# Question 5. Create a new column called Revenue using NumPy
import numpy as np
df["Revenue"] = np.multiply(df["Quantity"], df["Price"])
df

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
0,T001,C015,Books,7.0,167.0,02-02-2023,North,1169.0
1,T002,C004,Toys,4.0,374.0,17-02-2023,South,1496.0
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South,8472.0
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South,1520.0
4,T005,C022,Books,7.0,282.0,27-07-2024,West,1974.0
...,...,...,...,...,...,...,...,...
95,T096,C036,Furniture,10.0,2901.0,08-08-2023,North,29010.0
96,T097,C021,Clothing,9.0,1077.0,19-07-2024,North,9693.0
97,T098,C015,Clothing,7.0,643.0,13-08-2023,North,4501.0
98,T099,C005,Groceries,9.0,429.0,20-01-2024,South,3861.0
99,T100,C010,Furniture,8.0,1183.0,07-02-2024,North,9464.0

In [48]:
#Q6. Using NumPy, calculate the total revenue generated from all transactions in the dataset.
total_revenue = np.sum(df["Revenue"])
print(f"total_revenue generated from all transaction is {total_revenue}")

total_revenue generated from all transaction is 465529.66058002145

In [50]:
# Q7. Group the dataset by Product Category and calculate the total revenue generated by each category.
revenue_by_category = df.groupby("Product Category")["Revenue"].sum().round(2)
print(revenue_by_category)

Product Category
Beauty          27647.00
Books           29597.94
Clothing        85006.00
Electronics     93204.32
Furniture      129664.53
Groceries       11978.00
Sports          34484.00
Toys            53947.88
Name: Revenue, dtype: float64

In [55]:
# Question 8 Top 3 highest revenue and bottom 3 lowest revenue by category revenue
Category_revenue = df.groupby("Product Category")["Revenue"].sum().round(2)
Top_3 = Category_revenue.sort_values(ascending=False).head(3)
Bottom_3 = Category_revenue.sort_values().head(3)
print("Top 3 highest revenue by category:")
print(Top_3)
print("\nBottom 3 lowest revenue by category:")
print(Bottom_3)

Top 3 highest revenue by category:
Product Category
Furniture      129664.53
Electronics     93204.32
Clothing        85006.00
Name: Revenue, dtype: float64

Bottom 3 lowest revenue by category:
Product Category
Groceries    11978.00
Beauty       27647.00
Books        29597.94
Name: Revenue, dtype: float64

In [63]:
# Questin 9 region wise revenue and display min and maximum revenue by which region
Region_Revenue = df.groupby("Region")["Revenue"].sum()
print(Region_Revenue)
print("Region with the highest revenue:", Region_Revenue.idxmax(), "-" , Region_Revenue.max())
print("Region with the lowest revenue:", Region_Revenue.idxmin(), "- ", Region_Revenue.min())

Region
East     126232.044039
North    153244.353383
South    104855.736842
West      81197.526316
Name: Revenue, dtype: float64
Region with the highest revenue: North - 153244.35338345866
Region with the lowest revenue: West -  81197.52631578947

In [71]:
# Question
import numpy as np

# Convert Date column into datetime
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)

# Extract Month
df["Month"] = df["Date"].dt.month

# Monthly Revenue
monthly_revenue = df.groupby("Month")["Revenue"].sum()

print("Monthly Revenue:")
print(monthly_revenue)

# Mean Revenue
print("\nMean Revenue:", np.mean(df["Revenue"]))

# Median Revenue
print("Median Revenue:", np.median(df["Revenue"]))

# Standard Deviation
print("Standard Deviation:", np.std(df["Revenue"]))

Monthly Revenue:
Month
1     43994.000000
2     33028.000000
3     10557.000000
4     57298.526316
5     27915.000000
6     28190.000000
7     47851.292159
8     76958.000000
9     30719.105263
10    38017.000000
11    27662.736842
12    43339.000000
Name: Revenue, dtype: float64

Mean Revenue: 4900.312216631804
Median Revenue: 3282.1052631578946
Standard Deviation: 4721.171795257337